#!/bin/bash
set -e

dataloader() {
    java -cp dataloader.jar:/opt/app/libs/* -Dsalesforce.config.dir="${1}" "${@:2}"
}

encryption_key() {
    CMD="com.salesforce.dataloader.security.EncryptionUtil"
    KEY="configs/encryption.key"

    if [ ! -f "$KEY" ]; then
        dataloader "configs" "$CMD" "-k" "$KEY"
    fi

    dataloader "configs" "$CMD" "$1" "$2" "$KEY"
}

case "$1" in
    "decrypt")
        if [ -z "$2" ]; then
            echo "You must provide the string to decrypt"
            exit 0
        fi

        encryption_key "-d" "$2"
        ;;
    "encrypt")
        if [ -z "$2" ]; then
            echo "You must provide the string to encrypt"
            exit 0
        fi

        encryption_key "-e" "$2"
        ;;
    "process")
        CMD="com.salesforce.dataloader.process.ProcessRunner"

        if [ -z "$2" ]; then
            echo "You must provide the configs/ config folder"
            exit 0
        fi

        if [ -z "$3" ]; then
            echo "You must provide the process name"
            exit 0
        fi

        dataloader "configs/$2" "$CMD" "process.name=$3"
        ;;
    *)
        echo "Invalid operation. You must specify either 'decrypt', 'encrypt' or 'process'."
        exit 0
esac
